apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260601-004618-yfpzsnsqrp9z-service
spec:
  selector:
    app: enterprise-system-20260601-004618-yfpzsnsqrp9z
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
